### ISSUE TITLE
[Virus report] - ClamTk found  "PUA.Win.Trojan.Xored-1" in this very popular package.

### ISSUE THREAD

**Issue by dalerka** [jensyt/imurmurhash-js#1]
Hey! The ClamTk virus scan (on MX Linux 18.3 x64) reports: 

../.cache/yarn/v4/npm-imurmurhash-0.1.4-9218b9b2b928a238b13dc4fb6b6d576f231453ea/node_modules/imurmurhash/imurmurhash.min.js      PUA.Win.Trojan.Xored-1               
../.cache/yarn/v1/npm-imurmurhash-0.1.4-9218b9b2b928a238b13dc4fb6b6d576f231453ea/.yarn-tarball.tgz                                PUA.Win.Trojan.Xored-1               

p.s.: apologies if this isn't the right place to report.

**Comment by pepf** [comment]
Hey, just wanted to respond here.

I dont think theres a "virus" in this package, checking the md5 hash of imurmurhash.min.js in the npm package and the one from this repo gives me identical results, so no tampering afaik. I assume npm actually checks this already so maybe this is unnecessary..

```
▶ md5 imurmurhash.min.js
MD5 (imurmurhash.min.js) = 52d2eb410de1c9e0758ef562289289fa
```

**Comment by coderextreme** [comment]
As mentioned, it's a trojan, not a virus.  Please work with clamav getting it delisted, please, much appreciated.  I have never seen 12,000,000 weekly downloads before. If this is malware, a lot of people are going to be affected!

**Comment by coderextreme** [comment]
Also, figure out what minifier you use, and check to see if it's malware or not.

**Comment by jensyt** [comment]
I just audited the minified code and this is a false positive.

**Comment by jfoclpf** [comment]
@jensyt All my projects are getting hit by clamAV, you should really consider ping those guys of clamAV, because people may get scared

```
/home/joao/dev/form-for-parking-violation/node_modules/imurmurhash/imurmurhash.min.js: PUA.Win.Trojan.Xored-1 FOUND
/home/joao/dev/my-react-app/node_modules/imurmurhash/imurmurhash.min.js: PUA.Win.Trojan.Xored-1 FOUND
/home/joao/dev/police-finder/node_modules/imurmurhash/imurmurhash.min.js: PUA.Win.Trojan.Xored-1 FOUND
/home/joao/dev/paragraph-builder/node_modules/imurmurhash/imurmurhash.min.js: PUA.Win.Trojan.Xored-1 FOUND
/home/joao/dev/words-pt/node_modules/imurmurhash/imurmurhash.min.js: PUA.Win.Trojan.Xored-1 FOUND
/home/joao/dev/geoptapi/node_modules/imurmurhash/imurmurhash.min.js: PUA.Win.Trojan.Xored-1 FOUND
/home/joao/dev/cordova-import-npm/node_modules/imurmurhash/imurmurhash.min.js: PUA.Win.Trojan.Xored-1 FOUND
/home/joao/dev/delp/node_modules/imurmurhash/imurmurhash.min.js: PUA.Win.Trojan.Xored-1 FOUND
/home/joao/dev/bike-reporter/node_modules/imurmurhash/imurmurhash.min.js: PUA.Win.Trojan.Xored-1 FOUND
/home/joao/dev/autocosts/node_modules/imurmurhash/imurmurhash.min.js: PUA.Win.Trojan.Xored-1 FOUND
```

**Comment by jensyt** [comment]
I submitted a false positive report to clam AV.

**Comment by woss** [comment]
still is not resolved 
![image](https://user-images.githubusercontent.com/80440/164531597-4efa13d9-7d57-4461-906f-ce55c76224ab.png)

**Comment by 0xebjc** [comment]
same here, 
![False_positive](https://user-images.githubusercontent.com/28933033/164536600-0ad7ac0d-dbef-4df3-af87-af8a34c5ff36.PNG)

**Comment by zied-ellouze** [comment]
@jensyt did you get any feedback from clamav?

**Comment by jensyt** [comment]
@zied-ellouze I did not. I re-submitted the false positive again just now.

**Comment by cdr-chakotay** [comment]
It is still a thing sadly. Got it reported today

**Comment by blockchainchad** [comment]
Still happening.

**Comment by SamBehm** [comment]
(13/12/22) still reported :/

**Comment by edunfelt** [comment]
Popped up in my scan today.

**Comment by sephentos** [comment]
Still happening

**Comment by rocrandall** [comment]
still happening

**Comment by NullVoxPopuli** [comment]
still happening :upside_down_face:

**Comment by anthony-evans** [comment]
It still happens

**Comment by WarrenMarshall** [comment]
Still happening.

**Comment by sepehr** [comment]
Instead of updating the thread on this repo, we should probably knock on clamtk door to get their attention?

**Comment by sepehr** [comment]
We should probably knock on clamav door? Here you could submit a false positive report. If they get enough of such reports, it might do something.

https://www.clamav.net/reports/fp

**Comment by lucasctd** [comment]
Interesting my clamav just reported this file:

![image](https://github.com/jensyt/imurmurhash-js/assets/5876679/b383e352-92ea-4c4a-843b-f7592138aa2e)
However, when I scanned it on VirusTotal it says it's clean...
![image](https://github.com/jensyt/imurmurhash-js/assets/5876679/9fb37d2c-799b-492d-a939-b700fcaf0ffa)

```sh
clamscan --version
ClamAV 0.103.9/27052/Thu Oct  5 07:38:26 2023
```

**Comment by coderextreme** [comment]
Look at the file.  False positive.

**Comment by tetoNidan** [comment]
I get this false positive as well.

**Comment by Raphides** [comment]
Here to say it is still happening 😢

**Comment by sephentos** [comment]
Well, guys...

Nothing has happened here in three years and the repo here hasn't been updated in 10 (!) years.
I would say it's time to stop using this package and let everyone who uses it know about it.

**Comment by philippn** [comment]
For the record, we have also encountered this bug and it seems this is more likely an issue with ClamAV than this particular library.

Our analysis showed that the false positive occurs with ClamAV 1.1.2 with database version 27101. However, it does not occur with  ClamAV 1.0.4 (database version 27073) or ClamAV 1.1.3 (with same database version 27101). Hence one way to work around this issue is to simply update ClamAV.

Hope that helps!

**Comment by jensyt** [comment]
The repo hasn't been updated because there's nothing to update, unfortunately. I've audited the minified code and submitted false positive reports to ClamAV. Based on @philippn it sounds like the issue is resolved with a ClamAV update. At this point, I believe anyone encountering this issue can either:
1. Update ClamAV
2. If you're not using the incremental functionality of this package, move to one of the multiple alternatives with no loss of performance.
3. If you are using the incremental functionality of this package, evaluate the alternatives for whether the performance difference matters for your use case.

For the record, the most common packages using this one (e.g. NPM) did not use the incremental functionality the last time I checked a few years ago. If you're getting this false positive from one of those, you can try to convince them to change and it should have no negative impact.

**Comment by argosopentech** [comment]
Clam flagged this file for me and it seems like a false positive.

```
PUA.Win.Trojan.Xored-1

/home/myuser/.vscode/extensions/github.copilot-1.155.0/dist/extensionUninstalled.js
```

**Comment by abdullah1116** [comment]
still happening

**Comment by devHk0Matsu4zkrei** [comment]
Sep 8 2024 I did the last update in clam tk and still reported as potential unwanted program PUA.Win.Trojan.Xored-1 Xored-1 seems a possible spies behave. And when I delete it, it crashes my JavaScript solidity practices with node.  At windows?

**Comment by All3xJ** [comment]
still happening

**Comment by Rz-Rz** [comment]
still happening

**Comment by barrymcvey** [comment]
still happening

**Comment by alexarobu** [comment]
still happening :frowning_face:

**Comment by mj1911** [comment]
`/usr/lib/node_modules/node-gyp/node_modules/imurmurhash/imurmurhash.min.js   PUA.Win.Trojan.Xored-1`
`/usr/lib/node_modules/npm/node_modules/imurmurhash/imurmurhash.min.js   PUA.Win.Trojan.Xored-1`

So then what... are we forced to question all PUA.Win.Trojan.Xored-1 because ClamAV won't fix their false positives?

This would have been resolved over 4 years ago if there was any consequence to ClamAV.  Instead, they ignore us.

There should be a "user trust rating" which all AV's have, and WE assign to them.

**Comment by alexandrglm** [comment]
Well, since ClamAV didn't updated this false-positive report, and, as long as many other npm packages ( and browser-cached files for deployments which uses this or another similar packages ) are also reported as _PUA - Xored1_, taking in count that **this closed issue clarifies in a proper way everything** related to, I'm content to say I will stay using _imurmurhash_ as before :-)

**Comment by kartheekgp** [comment]
Hi team, seeing this with the latest scan with ClamTk on Raspberry pi 5:

`/node_modules/imurmurhash/imurmurhash.min.js 
/node_modules/npx/node_modules/npm/node_modules/imurmurhash/imurmurhash.min.js
/node_modules/npx/node_modules/imurmurhash/imurmurhash.min.js
/.nvm/versions/node/v22.17.0/lib/node_modules/npm/node_modules/imurmurhash/imurmurhash.min.js
`

They are flagged with - 
`PUA.Win.Trojan.Xored-1`

System info:
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

EDIT: Looks like ClamTk is no longer maintained : https://github.com/dave-theunsub/clamtk/issues

**Comment by joshbera** [comment]
false positives should be reported here:

https://www.clamav.net/reports/fp

**Comment by EpicWink** [comment]
You can also report false reports using the command-line tool `clamsubmit`:

```shell
clamsubmit -e '<your email>' -N '<your name>' -p <path to [archive of] imurmurhash.min.js> -V PUA.Win.Trojan.Xored-1
```

---

I can confirm that this is likely an actual false-positive, because running [Prettier](https://www.npmjs.com/package/prettier) on the minified file causes ClamAV to stop detecting the file as an PUA:

```shell
$ clamscan --no-summary --detect-pua ./imurmurhash.min.js
./imurmurhash.min.js: PUA.Win.Trojan.Xored-1 FOUND

$ npm exec prettier -- -w ./imurmurhash.min.js
./imurmurhash.min.js

$ clamscan --no-summary --detect-pua ./imurmurhash.min.js
./imurmurhash.min.js: OK
```

**Comment by RolH1992** [comment]
I also have a possible false flag here as well. I use five-server for front end code .config/VSCodium/CachedExtensionVSIXs/.trash/yandeu.five-server-0.3.11-universal: PUA.Win.Trojan.Xored-1 FOUND.

**Comment by parhammed** [comment]
still happening after almost 6 years
